### ISSUE TITLE
![image](https://user-images.githubusercontent.com/71161018/93008789-91bbc180-f53e-11ea-9192-812725fe8202.png)

### ISSUE THREAD

**Issue by successrequiresKnowledge** [krishpranav/Phishing#2]
![image](https://user-images.githubusercontent.com/71161018/93008789-91bbc180-f53e-11ea-9192-812725fe8202.png)

__Originally posted by @successrequiresKnowledge in https://github.com/krishpranav/Backdoorcreator/issues/1__

**Comment by krishpranav** [comment]
Nice.

**Comment by krishpranav** [comment]
ok give me your gmail id i will mail you some important stuffs about teaching

**Comment by krishpranav** [comment]
is that okay??
